### ISSUE TITLE
Error: Result 1 is not a length 1 atomic vector

### ISSUE THREAD

**Issue by henry090** [andrie/deepviz#3] opened 2018-10-10 07:01 UTC
I am running the code snippet from the description.

```r
require(keras)
library(deepviz)
library(magrittr)

model <- keras_model_sequential() %>%
  layer_dense(10, input_shape = 4) %>%
  layer_dense(2, activation = "sigmoid")

model %>% plot_model()
```

I get an error:

```
Error: Result 1 is not a length 1 atomic vector
```

`plot_model()`  works only for the following Keras model:

```r
model <- local({
  main_input <- layer_input(shape = c(100), dtype = 'int32', name = 'main_input')

  lstm_out <- main_input %>%
    layer_embedding(input_dim = 10000, output_dim = 512, input_length = 100) %>%
    layer_lstm(units = 32)

  auxiliary_output <- lstm_out %>%
    layer_dense(units = 1, activation = 'sigmoid', name = 'aux_output')

  auxiliary_input <- layer_input(shape = c(5), name = 'aux_input')

  main_output <- layer_concatenate(c(lstm_out, auxiliary_input)) %>%
    layer_dense(units = 64, activation = 'relu') %>%
    layer_dense(units = 64, activation = 'relu') %>%
    layer_dense(units = 64, activation = 'relu') %>%
    layer_dense(units = 1, activation = 'sigmoid', name = 'main_output')

  keras_model(
    inputs = c(main_input, auxiliary_input),
    outputs = c(main_output, auxiliary_output)
  )
})

model %>% plot_model()
```

**Comment by andrie** [comment] 2018-10-12 09:29
This is a duplicate of #2, which I closed because we couldn't reproduce.  I still can't reproduce.

But in that issue report you said that you had error messages during installation, which is different issue.  That's why I asked you to create a new issue, with as much information as possible about the installation errors you get.

**Comment by henry090** [comment] 2018-10-12 09:44
_**I  am not interested in installation errors, I just wanted to notify you about that. Your package is not able to automatically install dependent packages.**_


> This is a duplicate of #2, which I closed because we couldn't reproduce. I still can't reproduce.

Do you want to say that if you cannot reproduce that error, then you do not care about this error? So, it makes sense to close the issue just because of that? 

> But in that issue report you said that you had error messages during installation, which is different issue.

Interesting! I thought that heading is enough to understand which problem I really have.
<img width="977" alt="screen shot 2018-10-12 at 13 39 30" src="https://user-images.githubusercontent.com/38523699/46861750-6f860a00-ce24-11e8-9dc4-32d996e526a5.png">

**Comment by andrie** [comment] 2018-10-12 10:01
Thank you for your report.  I understand that you have a problem, but what I'm saying is I can't reproduce this, so there's not much I can do about that, until I can find a way of reproducing.

It is possible, though, that your installation is incorrect, which might explain why the problem occurs.

I *am* interested in fixing those installation errors, which is why I'm requesting more information.

**Comment by henry090** [comment] 2018-10-12 20:28
I have tested this [link](https://tensorflow.rstudio.com/keras/articles/about_keras_models.html).
Sequential model does NOT work with plot_model(). `model <- keras_model_sequential() `
But functional model works fine. 
<img width="610" alt="screen shot 2018-10-13 at 00 26 57" src="https://user-images.githubusercontent.com/38523699/46892544-d801d500-ce7e-11e8-8732-181b14b027f8.png">

**Comment by msmith01** [comment] 2019-01-12 23:14
I get the same error which is strange because it was working and then I closed R and opened it again and now I get the `Error: Result 1 is not a length 1 atomic vector`. The following example works:

```
model <- local({
  main_input <- layer_input(shape = c(100), dtype = 'int32', name = 'main_input')
  
  lstm_out <- main_input %>%
    layer_embedding(input_dim = 10000, output_dim = 512, input_length = 100) %>%
    layer_lstm(units = 32)
  
  auxiliary_output <- lstm_out %>%
    layer_dense(units = 1, activation = 'sigmoid', name = 'aux_output')
  
  auxiliary_input <- layer_input(shape = c(5), name = 'aux_input')
  
  main_output <- layer_concatenate(c(lstm_out, auxiliary_input)) %>%
    layer_dense(units = 64, activation = 'relu') %>%
    layer_dense(units = 64, activation = 'relu') %>%
    layer_dense(units = 64, activation = 'relu') %>%
    layer_dense(units = 1, activation = 'sigmoid', name = 'main_output')
  
  keras_model(
    inputs = c(main_input, auxiliary_input),
    outputs = c(main_output, auxiliary_output)
  )
})

model
model %>% plot_model()
```

However when I run something like the following:

```
model <- keras_model_sequential() %>%
  layer_lstm(units            = 100, 
             input_shape      = c(tsteps, 1), #takes the timesteps and number of features (i.e. univariate = 1)
             batch_size       = batch_size,
             return_sequences = TRUE, 
             stateful         = TRUE) %>% 
  layer_lstm(units            = 100, 
             return_sequences = TRUE, 
             stateful         = TRUE) %>% 
  layer_lstm(units            = 100, 
             return_sequences = TRUE, 
             stateful         = TRUE) %>% 
  layer_lstm(units            = 100, 
             return_sequences = TRUE, 
             stateful         = TRUE) %>% 
  layer_lstm(units            = 100, 
             return_sequences = TRUE, 
             stateful         = TRUE) %>% 
  layer_lstm(units            = 100, 
             return_sequences = TRUE, 
             stateful         = TRUE) %>% 
  layer_lstm(units            = 100, 
             return_sequences = FALSE, 
             stateful         = TRUE) %>% 
  layer_dense(units = 1)



model %>% 
  compile(loss = 'mae', optimizer = 'adam')

model %>% plot_model()
```

I get the error

**Comment by henry090** [comment] 2019-01-13 10:17
@msmith01 I'd suggest you use [Netron](https://github.com/lutzroeder/netron)

**Comment by msmith01** [comment] 2019-01-13 20:50
> @msmith01 I'd suggest you use [Netron](https://github.com/lutzroeder/netron)

Thats for Python

**Comment by henry090** [comment] 2019-01-13 20:54
> > @msmith01 I'd suggest you use [Netron](https://github.com/lutzroeder/netron)
> 
> Thats for Python

Just save the hdf.5 model and open with that Netron. It will plot it better than anything. IMO

**Comment by msmith01** [comment] 2019-01-13 21:00
> > > @msmith01 I'd suggest you use [Netron](https://github.com/lutzroeder/netron)
> > 
> > 
> > Thats for Python
> 
> Just save the hdf.5 model and open with that Netron. It will plot it better than anything. IMO

Apologies, I am a little bit confused on how I would do this in R.

**Comment by andrie** [comment] 2019-01-21 18:33
I updated my `keras` and `tensorflow` packages and now can replicate the problem.

**Comment by andrie** [comment] 2019-01-21 18:43
The internal representation of a model object changed, and now sequential models also have a `layers` element in the result of `get_config()`.

It's not clear when this changed, but for now simply assumes that the `model` object has this format.

Fixed in master branch.

**Closed** 2019-01-22 11:35 UTC
Labels: bug

**Comment by msmith01** [comment] 2019-01-22 19:10
Okay, I reinstalled keras and a few other packages and it seems to be working now.
